services:
  redis-db:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning
    volumes:
      - cache:/data
    restart: always

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis-db:6379
    ports:
      - "8001:8081"

  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis-db

volumes:
  cache:
    driver: local
